### ISSUE TITLE
零式异闻六根山预设，怨灵猛虎巨手扇形这一个配置，在零式难度下不显示

### ISSUE THREAD

**Issue by msew11** [Errerer/FFXIV_SPLPresets#2]
打零式时，踩了坑

参考这里的预设是显示的
https://github.com/PunishXIV/Splatoon/blob/main/Presets/Endwalker%20content/Duties/Mount%20Rokkon(Normal%26Savage).md

我看相对于官库预设作了一些改动，while casting指定了`35873|横扫`
![image](https://github.com/Errerer/FFXIV_SPLPresets/assets/23654758/e5b63e81-0c59-4349-98c0-2152ae3bb8c2)
把这个横扫√去掉就能在零式正常显示了。

**Comment by Errerer** [comment]
OK 谢谢提交bug 改日修复
